[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/*",
    "target/*",
    "node_modules/*",
    "dist/*",

    # Generated schema files
    "schema/*",

    # Package lock files contain hashes and encoded data
    "package-lock.json",
    "Cargo.lock",

    "mermaid.min.js",
]

[default]
extend-ignore-re = [
]
check-filename = true

[default.extend-identifiers]
ndJsonStream = "ndJsonStream"
