[workspace]
resolver = "2"
members = ["hangar-config",
    "mantle-agent",
    "mantle-hub",
    "mantle-shared",
    "tui-sidebar",
    "tui-popup",
    "ssh-proxy",
    "effector",
    "docker-spawner",
]
